### ISSUE TITLE
Add import statement

### ISSUE THREAD

**Issue by anderskristian** [lmivan/gr8conf2015-springboot#1]
Hi Ivan
Super presentation yesterday

I have cloned your demo
And seen that logGenerator.groovy works better having...

import org.springframework.scheduling.annotation.EnableScheduling

Thanks again for a great presenstion
/Anders

**Comment by ilopmar** [comment]
Thank you very much. I'm glad you like it.

Which version of Spring Boot are you using?

For my current version it works great:

```
$ spring version
Spring CLI v1.2.3.RELEASE
```

Regards, Iván.

**Comment by anderskristian** [comment]
spring --version
Spring CLI v0.5.0.M6
/Anders
PS: I will upgrade :-)

**Comment by ilopmar** [comment]
That's a very old version :-P

**Comment by anderskristian** [comment]
Yes it was old
Things goes fast

On my machine it still needs an import statement.
The class EnableScheduling was not imported 
It is used: in line 7 in the code, so I believe it needs to be declared ....

/Anders
PS: You said yesterday that you would update the samples on github. 
and maybe you have not updated all :-)

**Comment by ilopmar** [comment]
Ok, I reviewed the file and it includes the import:

https://github.com/lmivan/gr8conf2015-springboot/blob/master/tail-monitor-app/logGenerator.groovy#L4

Did you cloned the right repository?

**Comment by anderskristian** [comment]
I cloned the repository that this issue is part off..
When I open the file logGenerator.groovy from the github web I still do not see the import statement for class EnableScheduling

When I press the link you made in above I see a file that does NOT contain import of class EnableScheduling. I also see that it uses EnableScheduling

Regards Anders

**Comment by ilopmar** [comment]
Ouch, you're right. I mix up both imports.

**Comment by ilopmar** [comment]
I've added the import and pushed the new changes.

Thank you very much.

**Comment by anderskristian** [comment]
Super
In the mean time I made a pull request... with the same thing..
Hereby I have learned to make a change to a file and make a pull reuest..
(I did not know it was so easy...)
You can use it or not... (The change is small anyway)
Have a very good weekend 
/Anders

**Comment by ilopmar** [comment]
Yes, it's pretty simple contribute to other projects. 

Thank you very much. I hope to see you at Greach next year.

Regards, Iván.
